### ISSUE TITLE
Failing tests on Windows

### ISSUE THREAD

**Issue by cmb69** [zeriyoshi/php-ext-orng#25]
There are 6 test failures on Windows (some are not matching the expectations, some even segfault). This is apparently due to https://github.com/zeriyoshi/php-ext-orng/blob/792dbd680be362bbf263f319095970286b4d2890/rng/glibcrand.h#L33-L38

`RAND_MAX` is `0x7fff` on Windows (x64 as well as x86). The comment on top appears to be wrong (possibly outdated?), since `rand_r()` is not called anywhere. Defining `ORNG_GLIBCRAND_RAND_MAX` to `0x7fffffff` lets all tests pass on Windows.

**Comment by cmb69** [comment]
Details regarding the failing tests: https://ci.appveyor.com/project/zeriyoshi/php-ext-orng/builds/36975061/job/o9plej44kxr78x4d

**Comment by zeriyoshi** [comment]
This is an omission that I checked when I copied the implementation.
This problem has been fixed. Thanks! d0195355143bc311bce76317ada0c0fab090cb32
