### ISSUE TITLE
Package is marked as stable although version is 0.0.2

### ISSUE THREAD

**Issue by cmb69** [zeriyoshi/php-ext-orng#26]
I assume that this was just an oversight in https://github.com/zeriyoshi/php-ext-orng/blob/792dbd680be362bbf263f319095970286b4d2890/package.xml#L19-L22

**Comment by zeriyoshi** [comment]
Oops, it's unstable. fixed: ed8f133e233ffe9958dc6c78f22597a4f4c95822 2e68e78c6b9efd6e87034f95b79c78ba7f3c242e
