### ISSUE TITLE
CI: Testing on more environments

### ISSUE THREAD

**Issue by zeriyoshi** [zeriyoshi/php-ext-orng#4]
We need to add CI test in the following environments.

- Alpine Linux: another libc (musl-libc) environment, use case: k8s.
- macOS (optional): another unix environment, use case: local-development.
- Windows (optional): non-*nix environment.

**Comment by zeriyoshi** [comment]
add macOS: 249b97ea8e4daa2dab3990bc962c5fbca523aa48

**Comment by cmb69** [comment]
Windows CI: PR #23

**Comment by zeriyoshi** [comment]
We've covered all the desired environments! Thank you!
